aboutpage/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "aboutpage"

urlpatterns = [
    path('', views.about, name = "about"),
    path('question/', views.question_page, name = "question_page")
]

schedule/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "schedule"

urlpatterns = [
    path('', views.list_schedule, name = "list_schedule"),
    path('create-schedule', views.create_schedule, name = "create"),
    path('delete/<id>', views.delete_schedule, name = 'delete')
]

story_alwan/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aboutpage.urls')),
    path('schedule/', include('schedule.urls'))
]

aboutpage/models.py
from django.db import models

# Create your models here.

schedule/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Schedule(models.Model):
    kategori = [
        ('Academic', 'Academic'),
        ('Organization', 'Organization'),
        ('Personal', 'Personal'),
        ('Other', 'Other')
    ]

    day = models.CharField(max_length=9)
    date = models.DateField(null=True, editable=True)   
    hour = models.TimeField(null=True, editable=True)
    activity_name = models.CharField(max_length=20)
    place = models.CharField(max_length=30)
    category = models.CharField(max_length=10, choices=kategori)
    author = models.ForeignKey(User, default=1, on_delete=models.CASCADE)

    def __str__(self):
        return self.activity_name

schedule/forms.py
from django import forms
from . import models

class DateInput(forms.DateInput):
    input_type = 'date'

class TimeInput(forms.TimeInput):
    input_type = 'time'

class CreateModelSchedule(forms.ModelForm):
    class Meta:
        model = models.Schedule
        fields = [
            'date',
            'hour',
            'activity_name',
            'place',
            'category'  
        ]
        widgets = {
            'date': DateInput(),
            'hour': TimeInput()
        }

aboutpage/views.py
from django.shortcuts import render

# Create your views here.
def about(request):
    return render(request, 'about.html')

def question_page(request):
    return render(request, 'question.html')

schedule/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Schedule
from . import forms

# Create your views here.
def list_schedule(request):
    schedules = Schedule.objects.all()
    response = {
        'schedules': schedules
    }
    return render(request, 'list_schedule.html', response)

def create_schedule(request):
    form = forms.CreateModelSchedule(request.POST or None)
    if form.is_valid():
        obj = form.save()
        obj.day = obj.date.strftime("%A")
        obj.save()
        return redirect('schedule:list_schedule')
    response = {
        'form': form
    }
    return render(request, 'create_schedule.html', response)

def delete_schedule(request, id):
    schedule = Schedule.objects.filter(id=id)[0]
    schedule.delete()
    return redirect('schedule:list_schedule')

aboutpage/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %} About Me {% endblock %}

{% block content %}

    <div class="landing-section bg-overlay">
        <h2 class = "text-center"> 
            Hi There ! <br>
            Welcome to my website
        </h2>

        <div class="button text-center" id = "button-read">
            <a href="{% url 'aboutpage:about' %}#about" id = "btn">
                READ MORE
            </a>

        </div>
    </div>

    <div class="about-section" id = "about">
        <div class="about-container">
            <div class="img-container">
                <img src="/static/images/bg-alwan.png" alt="this-is-me" class="img-alwan">
            </div>

            <div class="desc-container">
                <h2 class="about-header text-center">
                    ABOUT ME
                </h2>

                <p id = "desc">
                    My Name is Alwan. I am currently studying Computer Science at the Faculty of Computer Science at the University of Indonesia. 
                    <br>  <br>
                    I like to learn about new stuff. I also like
                    to socialise with everyone. I prefer working together with a team rather than working alone.    
                </p>
            </div>

        </div>  
    </div>

    <div class="education-section" id = "edu">
        <div class="education-container">
            <div class="edu-box">
                <h2 class = "text-center" > EDUCATIONS </h2>
            </div>

            <div class="content-container">
                
                <div class="content-1">
                    <div class="ui-wrapper">
                        <img src="/static/images/ui-logo.svg" alt="logo-ui" id = 'logo-ui'>
                    </div>

                    <div class="desc-ui">
                        <p> Undergraduate Student of Computer Science
                            <br>
                            Currently in my Second Year of College at the Faculty of Computer Science
                            at the University of Indonesia </p>
                    </div>
                </div>

                <div class="content-2">
                    <div class="sma-wrapper">
                        <img src="/static/images/sma-logo.svg" alt="logo-sman-68" id = 'logo-sman-68'>
                    </div>

                    <div class="desc-sma">
                        <p> Science Studies
                            Graduated from High School where i mostly studied Math, Physics, Biology
                            and Chemistry. <br> Had an interest in programming ever since 10th Grade. </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="exp-section" id = "exp">
        <div class="exp-container">
            <div class="exp-box">
                <h2 class="text-center"> EXPERIENCE </h2>
            </div>

            <div class="content-container-2">
                <div class="side-image">
                    <img src="/static/images/side-bar.svg" alt="people-working">
                </div>

                <div class="exp-list">
                    <ul>
                        <li class="exps"> Staff of Academic and Leadership Department at BEM Fasilkom UI <br> <small> 2019 - Now </small> </li>
                        <li class="exps"> Staff of Musholla Prosperity Bureau at FUKI Fasilkom UI <br> <small> 2019 - Now </small> </li>
                        <li class="exps"> Mentor at PMB Fasilkom UI <br> <small> 2019 - Now </small> </li>
                        <li class="exps"> Staff of Innovative App Competition Division at COMPFEST 11 <br> <small> 2019 - Now </small></li>
                        <li class="exps"> Person in Charge of Equipment at PEMIRA IKM Fasilkom UI <br> <small> 2019 - Now </small> </li>
                    </ul>
                </div>
            </div>
                
        </div>
    </div>

    <div class="skills-section" id = "skill">
        <div class="skills-container">
            <div class="skill-box">
                <h2 class = "text-center"> Skills </h2>
        
            </div>

            <div class="circle-wrapper text-right"></div>

            <div class="skill-set d-flex justify-content-around align-items-center">
                <div class="logo-container text-center">
                    <img src="/static/images/java.svg" alt="java-logo" class="skills ">

                    <h5 class = "text-center"> Java  </h5>
                </div>

                <div class="logo-container">
                    <img src="/static/images/python.svg" alt="python-logo" class="skills">

                    <h5 class = "text-center"> Python </h5>
                </div>

                <div class="logo-container">
                    <img src="/static/images/html.svg" alt="html-logo" class="skills">

                    <h5 class = "text-center"> HTML </h5>
                </div>

                <div class="logo-container">
                    <img src="/static/images/css.svg" alt="css-logo" class="skills">

                    <h5 class = "text-center"> CSS </h5>
                </div>
                    
                <div class="logo-container">
                    <img src="/static/images/office.svg" alt="microsoft-office-logo" class="skills">

                    <h5 class = "text-center"> Microsoft Office </h5>
                </div>
            </div>

        
            <div class="circle-wrapper-2"></div>


        </div>
    </div>

    <div class="end-section bg-overlay d-flex flex-column justify-content-around">
        <h2 class = "text-center">
            LEARN MORE ABOUT ME
        </h2>

        <div class="social-container d-flex justify-content-around">
            <div class="ig-logo">
                <a href="https://instagram.com/alha1101/" target= "_blank">
                    <img src="/static/images/ig.svg" alt="ig-logo">
                </a>
            </div>

            <div class="twitter-logo">
                <a href="https://twitter.com/alwan_2" target = "_blank">
                    <img src="/static/images/twitter.svg" alt="twitter-logo">
                </a>
            </div>

            <div class="linked-logo">
                <a href="https://linkedin.com/in/alwan-harrits-363381180" target="_blank">
                    <img src="/static/images/linkedin-logo.svg" alt="linked-in-logo">
                </a>
            </div>

            <div class="fb-logo">
                <a href="https://facebook.com" target="_blank">
                    <img src="/static/images/fb.svg" alt="facebook-logo">
                </a>
            </div>
        </div>

    </div>

{% endblock %}

aboutpage/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="{% static 'css/aboutStyle.css' %}">
        <title> {% block title %} {% endblock %} </title>
    </head>

    <body>
        <div class="page-container">
                
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark navbar-right fixed-top" id = "navbar">
                <button class="navbar-toggler toggler-example" type="button" data-toggle="collapse" data-target="#navbarSupportedContent1"
                    aria-controls="navbarSupportedContent1" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"><i
                        class="fas fa-bars fa-1x"></i></span>
                </button>
                <div class="collapse navbar-collapse" id = "navbarSupportedContent1">
                    <ul class="navbar-nav ml-auto">
                        <li class="active">  <a href="{% url 'aboutpage:about' %}#about"> About </a> </li>
                        <li > <a href="{% url 'aboutpage:about' %}#edu"> Educations </a> </li>
                        <li > <a href="{% url 'aboutpage:about' %}#exp"> Experience </a> </li>
                        <li > <a href="{% url 'aboutpage:about' %}#skill"> Skills </a> </li>
                        <li > <a href="{% url 'aboutpage:question_page' %}"> F.A.Q </a> </li>
                        <li > <a href="{% url 'schedule:list_schedule' %}"> My Schedule </a> </li>
                    </ul>
                </div>
            </nav>

            {% block content %}
            {% endblock %}

        </div>

        

        <footer class="footer bg-dark">
                <div class="container text-center">
                    <small>Copyright &copy; Alwan Harrits</small>
                </div>                               
            </footer>

    </body>
</html>

aboutpage/templates/question.html
{% extends 'base.html' %}
{% load static %}

{% block title %} F.A.Q {% endblock %}

{% block content %}
    <div class="top-wrapper">
        <!-- <img src="assets/top-circle.svg" alt="" class="ellipse"> -->
        <h2 class = "text-center"> F.A.Q </h2>
    </div>

    <div class="question-section">

        <div class="question-container d-flex flex-column justify-content-around">
            <div class="blue-box d-flex justify-content-around" id = "question-1">
                <div class="question">
                    <h2> 1. How Old Are You ? </h2>
                </div>

                <div class="answer">
                    <h4> I Am 18 Years Old </h4>
                </div>
            </div>

            <div class="white-box d-flex justify-content-around" id = "question-2">
                <div class="question">
                    <h2> 2. How Long Have You Been Alive ? </h2>
                </div>

                <div class="answer">
                    <h4> I Have Been Alive For 18 Years </h4>
                </div>
            </div>

            <div class="blue-box">
                <div class="special  d-flex justify-content-around" id = "question-3">
                    <div class="question">
                        <h2> 3. What Is Your Favorite Color ? </h2>
                    </div>
            
                    <div class="answer">
                        <h4> Black </h4>
                    </div>
                </div>
            </div>

            <div class="white-box">
                <div class="special  d-flex justify-content-around" id = "question-4">
                    <div class="question">
                        <h2> 4. What Is The Answer To Life, 
                            <br>
                            Universe, And Everything ? 
                        </h2>
                    </div>
    
                    <div class="answer">
                        <h4> 42 </h4>
                    </div>
                </div>
            </div>
        </div>

        <div class="bot-wrapper">
            <h2>
                ""
            </h2>
        </div>
    </div>


{% endblock %}

schedule/templates/create_schedule.html
{% extends 'base.html' %}

{% block title %} Create Schedule {% endblock %}

{% block content %}

    <div class="create-container">
        <form action="{% url 'schedule:create' %}" method = "post" class = "create">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value = "Create">
        </form>
    </div>

{% endblock %}

schedule/templates/list_schedule.html
{% extends 'base.html' %}

{% block title %} My Schedule {% endblock %}

{% block content %}

    <div class="schedule-container">
        {% for schedule in schedules %}
            <div class="schedule">
                <h2> {{ schedule.activity_name }} </h2>
                <h4> {{ schedule.place }} , {{ schedule.day }}, {{ schedule.date }}, {{ schedule.hour }} </h3>
                <p>
                    {{ schedule.category }}
                </p>

                <a href="{% url 'schedule:delete' id=schedule.id %}"  >
                    <input type="button" value="Delete Schedule">
                </a>
            </div>
        {% endfor %}

        <div class="create-button">
            <a href="{% url 'schedule:create' %}">
                <input type="submit" formaction="{% url 'schedule:create' %}" value = "Create New Schedule">
            </a>
        </div>
    </div>

{% endblock %}